name: Deploy Storybook
on:
  push:
    branches: ["main"]
    paths:
      - 'src/**/*.stories.@(js|jsx|ts|tsx|mdx)'
      - '.storybook/**'
      - 'src/**/*.mdx'
      - 'src/**/*.stories.@(js|jsx|mjs|ts|tsx|)'
      - 'tokens/**/*.stories.@(js|jsx|ts|tsx|)'
      - 'tokens/**/*.mdx'
      - 'package.json'
      - 'pnpm-lock.yaml'

  pull_request:
    branches: ["main"]
    paths:
      - 'src/**/*.stories.@(js|jsx|ts|tsx|mdx)'
      - '.storybook/**'
      - 'src/**/*.mdx'
      - 'src/**/*.stories.@(js|jsx|mjs|ts|tsx|)'
      - 'tokens/**/*.stories.@(js|jsx|ts|tsx|)'
      - 'tokens/**/*.mdx'
      - 'package.json'
      - 'pnpm-lock.yaml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      # Viteとストーリーブックのキャッシュを設定
      - name: Cache build files
        uses: actions/cache@v4
        with:
          path: |
            storybook-static
            node_modules/.cache
            node_modules/.vite
          key: ${{ runner.os }}-vite-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-vite-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-vite-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm run build-storybook
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './storybook-static'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4